---
# kubernetes/config/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: reelmania-secrets
type: Opaque
data:
  # Base64 encoded values (Replace with your actual base64 encoded secrets)
  VITE_CLERK_PUBLISHABLE_KEY: "<base64-encoded-vite-clerk-publishable-key>"
  CLERK_SECRET_KEY: "<base64-encoded-clerk-secret-key>"
  USER_DATABASE_URL: "<base64-encoded-user-database-url>"
  VIDEO_DATABASE_URL: "<base64-encoded-video-database-url>"
  AZURE_STORAGE_CONNECTION_STRING: "<base64-encoded-azure-connection-string>"
  AZURE_STORAGE_ACCOUNT_NAME: "<base64-encoded-azure-account-name>"
  AZURE_SHARED_KEY: "<base64-encoded-azure-shared-key>"
  AZURE_BLOB_CONTAINER_NAME: "<base64-encoded-azure-blob-container-name>"
  CLERK_PUBLISHABLE_KEY: "<base64-encoded-clerk-publishable-key>"
  WEBHOOK_SIGNING_SECRET: "<base64-encoded-webhook-signing-secret>"
  

---