name: Deploy User Service to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - './**'  # Trigger only when changes are made in the user-service directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and Push Docker images for frontend to Docker Hub
        run: |
          docker build -t hussnainse/reelmania-user-service:latest ./backend/user-service
          docker push hussnainse/reelmania-user-service:latest

      # Step 5: Deploy Docker container to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reelmania-user-service'  # The name of the Azure Web App
          publish-profile: ${{ secrets.USER_SERVICE_USER_PROFILE }}  # Add publish profile in GitHub Secrets
          images: 'hussnainse/reelmania-user-service:latest'  # Container image to deploy
